site_name: MLWP Data Specs
site_description: Trait-based dataset validation specifications
repo_url: https://github.com/leifdenby/mlwp-data-specs

theme:
  name: material
  features:
    - navigation.expand
    - content.code.copy

markdown_extensions:
  - admonition
  - attr_list
  - def_list
  - footnotes
  - tables
  - pymdownx.highlight
  - pymdownx.superfences
  - toc:
      permalink: true

nav:
  - Home: index.md
  - Traits:
      - Space:
          - Grid: traits/space_grid.md
          - Point: traits/space_point.md
      - Time:
          - Forecast: traits/time_forecast.md
          - Observation: traits/time_observation.md
      - Uncertainty:
          - Deterministic: traits/uncertainty_deterministic.md
          - Ensemble: traits/uncertainty_ensemble.md
          - Quantile: traits/uncertainty_quantile.md
